name: Table Top CI/CD with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: lts/Hydrogen
        
    - uses: actions/checkout@v2
    - run: |
        touch ./.env
        # echo "${{ secrets.ENV }}" > ./.env
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Excute Remote SSH Commands Using SSH_PRIVATE_KEY
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop github-action-frontend
            docker rm github-action-frontend
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}
            docker run -d -p 80:80 --network=docker-network --name ${{ secrets.REPOSITORY_NAME }} name ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}
            docker system prune -f
